name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
        sudo apt-get install libfreetype-dev
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install libglu-dev
        sudo apt-get install libglew-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
