name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfreetype-dev
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install libglu-dev
        sudo apt-get install libglew-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
    - name: publish
      uses: actions/upload-artifact@v3
      with:
        name: GLSMAC-ubuntu-bin
        path: |
          bin/GLSMAC
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: README.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/GLSMAC
        asset_name: GLSMAC-x86_64-ubuntu-bin
        asset_content_type: application/octet-stream
