name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfreetype-dev
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install libglu-dev
        sudo apt-get install libglew-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Portable .
    - name: make
      run: make
    - name: pack
      run: tar zcvf release/GLSMAC-ubuntu-bin.tar.gz bin/
    - name: publish
      uses: actions/upload-artifact@v3
      with:
        name: GLSMAC-ubuntu-bin
        path: |
          .release/GLSMAC-ubuntu-bin.tar.gz
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: GLSMAC-v0.1
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps     - name: upload
        asset_path: ./release/GLSMAC-ubuntu-bin.tar.gz
        asset_name: GLSMAC-ubuntu-bin.tar.gz
        asset_content_type: application/gzip
